
= Elicit - The simpler find with the more complicated name

[quote, wordnik]
____
e-lic-it

- To bring or draw out (something latent); educe.
- To arrive at (a truth, for example) by logic.
- To call forth, draw out, or provoke (a reaction, for example).

https://www.wordnik.com/words/elicit
____

Elicit is simple command line utility to *elicit* files matching something given (or to *find* files, but turns out that name was already taken ;))

[WARNING]
This project was started with the intention to learn rust and not to replace find, but it may be useful for simple file searches.

[NOTE]
It now uses the awesome https://github.com/BurntSushi/walkdir[walkdir crate]. For a somehow working version (stackoverflows if there are no hits for a while, and potentially other bugs) without walkdir see the without_walkdir branch.

[NOTE]
Only tested on Linux (x86_64). Should theoretically be platform independent.

== Usage

- TODO general usage
[source, sh]
----
elicit [options] [starting-direcotry] pattern
----

=== Options

- --help +
  output a usage information
  
=== Examples

- find all files recursively from the current directory with "hello" in the name
+
[source, sh]
----
elicit hello
----

- find all files recursively in the home directory with "hello" in the name
+
[source, sh]
----
elicit ~/ hello
----
+
TODO what order makes more sense pattern dir or dir pattern?


- find all files recursively in the home directory that have "hello" and somewhere later ".adoc" in the name (not necessarily at the end)
+
[source, sh]
----
elicit ~/ "hello*.adoc"
----

- print usage on illegal use or --help

=== TODO Examples of piping output to other programs

- TODO rm, ls, cp, grep, file


=== Considered Alternative Syntax

Maybe it would be better to have an alternatively syntax that would be more sentence like.
[source, sh]
----
elicit regex "^hello.*\.adoc$" in ~/
elicit in ~/ "hello*.adoc" with depth of 1 and files only
----
(Probably not, at least not like this)

=== Considered additional features

==== Regex
Find all files recursively in the home directory where the name starts with "hello" and ends with ".adoc"
[source, sh]
----
elicit -r "^hello.*\.adoc$" ~/
elicit "^hello.*\.adoc$" ~/ --regex
----
Switch from simple mode to regex mode with -r or --regex somewhere in the line.
Probably only very rarely useful, elicit should be as simple as possible, for this usecase find should be used.
